name       : ant-bloody-gtk-theme
version    : 1.3.0
release    : 3
source     :
    - https://github.com/EliverLara/Ant-Bloody/archive/v1.3.0.tar.gz : 000887586e55b83c84491e508765b19054699a0d07319c00969bce3638d0473f
license    : GPL-3.0-or-later
component  : desktop.themes
summary    : Bloody variant of the Ant Theme
description: |
    Bloody variant of the Ant Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant-Bloody/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant-Bloody/index.theme
