name       : ant-bloody-gtk-theme
version    : 1.2.0
release    : 2
source     :
    - https://github.com/EliverLara/Ant-Bloody/archive/v.1.2.0.tar.gz : a6bffdafb290d71edf4f6afd98d2fc14642253e4e78a946d0cfe038c00fbda0a
license    : GPL-3.0
component  : desktop.themes
summary    : Bloody variant of the Ant Theme
description: |
    Bloody variant of the Ant Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant-Bloody/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant-Bloody/index.theme
